import { defineConfig } from "vitepress";

export default defineConfig({
  title: "lshbosheth Docs",
  description: "Markdown previews generated by Codex",
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "Home", link: "/" }
    ],
    sidebar: [
      {
        text: "Preview Docs",
        items: [
          { text: "Ranran GSAP Migration", link: "/ranran-gsap-migration" },
          { text: "Markdown Preview Site Plan", link: "/markdown-preview-site-plan" }
        ]
      }
    ]
  }
});
